name: Run Production Build and Cypress Tests

on:
  push:
    branches: [BakangMonei]
  pull_request:
    branches: [BakangMonei]

jobs:
  test:
    timeout-minutes: 360
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Install Playwright
        run: npm install playwright
      - name: Build
        run: npm run build
      - name: Start server
        run: npm start
